[package]
name = "monerito"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rocket = "=0.5.0-rc.3"
serde = "1.0.189"
chrono = "0.4.31"
reqwest = { version = "0.11.22", features = ["json"]}
